name: Traffic-1

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run-traffic:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Xvfb (Simulate GUI)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "Xvfb started with PID $!"

      - name: Install Dependencies (Playwright)
        run: |
          npm install playwright
          npx playwright install firefox

      - name: Run main.js with timeout
        run: |
          timeout 20400 node main.js || {
            echo "main.js completed or was terminated after 5h40m"
            exit 0
          }

      - name: Upload Screenshot if Login Fails
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failed-login-screenshot
          path: failed-login.png
          if-no-files-found: ignore

      - name: Clean up Xvfb
        if: always()
        run: |
          echo "Cleaning up Xvfb..."
          pkill -f Xvfb || true
          echo "Job completed, exiting with status 0"
          exit 0

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
